"""add_performance_indexes

Revision ID: 7f0a3fa7dc6b
Revises: b1c2d3e4f5g6
Create Date: 2026-03-03 16:12:16.830257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f0a3fa7dc6b'
down_revision: Union[str, None] = 'b1c2d3e4f5g6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admission_updates_id', table_name='admission_updates')
    op.drop_table('admission_updates')
    op.create_index('ix_attempt_started_at', 'exam_attempts', ['started_at'], unique=False)
    op.create_index('ix_attempt_student_status', 'exam_attempts', ['student_id', 'status'], unique=False)
    op.create_index('ix_attempt_student_type', 'exam_attempts', ['student_id', 'exam_type'], unique=False)
    op.create_index('ix_ps_student_status', 'practice_sessions', ['student_id', 'status'], unique=False)
    op.create_index('ix_ps_subject', 'practice_sessions', ['subject_id'], unique=False)
    op.create_index('ix_q_exam_type_active', 'questions', ['exam_type', 'is_active'], unique=False)
    op.create_index('ix_q_subject_active', 'questions', ['subject_id', 'is_active'], unique=False)
    op.create_index('ix_q_topic_active', 'questions', ['topic_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_university_news_id'), 'university_news', ['id'], unique=False)
    op.create_index(op.f('ix_university_news_university_id'), 'university_news', ['university_id'], unique=False)
    op.alter_column('users', 'class_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_constraint('users_selected_course_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_selected_university_id_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_selected_university_id_fkey', 'users', 'universities', ['selected_university_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('users_selected_course_id_fkey', 'users', 'courses', ['selected_course_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'class_level',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_university_news_university_id'), table_name='university_news')
    op.drop_index(op.f('ix_university_news_id'), table_name='university_news')
    op.drop_index('ix_q_topic_active', table_name='questions')
    op.drop_index('ix_q_subject_active', table_name='questions')
    op.drop_index('ix_q_exam_type_active', table_name='questions')
    op.drop_index('ix_ps_subject', table_name='practice_sessions')
    op.drop_index('ix_ps_student_status', table_name='practice_sessions')
    op.drop_index('ix_attempt_student_type', table_name='exam_attempts')
    op.drop_index('ix_attempt_student_status', table_name='exam_attempts')
    op.drop_index('ix_attempt_started_at', table_name='exam_attempts')
    op.create_table('admission_updates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admission_updates_pkey')
    )
    op.create_index('ix_admission_updates_id', 'admission_updates', ['id'], unique=False)
    # ### end Alembic commands ###
